### ISSUE TITLE
[Inference] Implement multi-class labels

### ISSUE THREAD

**Issue by charlieforward9** [charlieforward9/visualPT#113]
From [09.27.2023 Meeting](https://github.com/orgs/VisualPT/discussions/11#discussioncomment-7135903)

Failure Criteria (for all test conditions)
Eyes open 1st (Conditions # 2 and # 5 - eyes-closed)
Arms windmill or abduct to maintain balance (all conditions).
Trunk flexes (sidebends) to maintain balance. (all conditions).
Legs step outside the Base of Support (all conditions).

https://docs.google.com/document/d/12xg0lQwGTeDL1MKKouTuwHUHwSxkiUoPY7iof2cYl-o/edit?usp=sharing

**Comment by charlieforward9** [comment]
@Timothyrichpt @DrBubbles42  I switched up the validation interface a little to ensure we have the most flexibility with labeling. Instead of trying to do classification while we collect, I am leaving all of the classifications to be done in the validation phase. 

![IMG_F0872F53F687-1](https://github.com/VisualPT/visualPT/assets/62311337/f1e57e2e-04c9-468d-be7e-78c99f6f0bd8)

This will help the data collection process be focused on collection accuracy, instead of labeling accuracy. This should help our data be more consistent as we move forward.

**Comment by charlieforward9** [comment]
@DrBubbles42 

Here are the new classifications that I have defined:

```dart
const Map<int, String> classifications = {
  -1: "invalid",
  0: "static",
  1: "arms uncrossed",
  2: "trunk flex",
  3: "feet separated",
};
```

**Comment by Timothyrichpt** [comment]
For conditions VisualPT/visualPT#2 and VisualPT/visualPT#5 I wonder if there would be away the algorithm could detect if they open their eyes?

**Comment by charlieforward9** [comment]
There are some face landmark models we could look at integrating, but this will take some time to address. Since the basic labels are completed, we can continue discussing this in the new issue VisualPT/visualPT#210

**Comment by DrBubbles42** [comment]
@Timothyrichpt are these all the cases we would want to expand on?

The eye opening is possible but it's definitely a stretch. We would need another model for just the face as Charlie said.

**Comment by Timothyrichpt** [comment]
I do not think we need eye-opening for our MVP.

If it’s a distraction or too many additional resources, I would say let’s leave it for later and just focus on static v. sway.


Love Your Life!

Tim


Want to schedule a call with Tim?

Put yourself on Tim's calendar here:

Calendly.com/Grow-With-Tim<https://calendly.com/grow-with-tim>


Tim Richardson, PT

Franchise Regional Consultant

Central Region, USA


FYZICAL LLC

World Headquarters

Bayou Professional Center

1751 Mound Street, <x-apple-data-detectors://2/1> Suite 101<x-apple-data-detectors://2/1>

Sarasota, Florida  34236<x-apple-data-detectors://2/1>


Mobile:  1.941.623.6109<tel:1.941.623.6109>


"Spelled Different Because We Are Different"


FYZICAL is Changing Lives and Changing Healthcare for Millions of Americans by Helping People Live Independently in Their Homes Without Fear of Falling.

On Oct 5, 2023, at 2:08 PM, Nicholas Fox ***@***.***> wrote:

﻿

@Timothyrichpt<https://github.com/Timothyrichpt> are these all the cases we would want to expand on?

The eye opening is possible but it's definitely a stretch. We would need another model for just the face as Charlie said.
