### ISSUE TITLE
[Validation] Improved Controls

### ISSUE THREAD

**Issue by Timothyrichpt** [charlieforward9/visualPT#77]
In this situation, I just validated all the data and there's nothing left to validate.

Could we tell the user that all their data is validated and they need to do another test?

https://github.com/VisualPT/visualPT/assets/124405841/ecb00023-dcf7-4024-b411-e369a248faee

**Comment by charlieforward9** [comment]
> It would be easy to click “back“ and capture the frames and label them correctly and still go through the validation process quickly if we had the “back“ button.

@Timothyrichpt It sounds like you're asking about being able to re-label a validated frame. Is that correct?

**Comment by Timothyrichpt** [comment]
There are a lot of frames to validate, even with just six tests I did on Wednesday.

I click quickly, sometimes before the frame even loads. The “true sway” condition only lasts for one frame. Sometimes I have clicked past it and labeled it “false” before the frame has loaded.

Would be good to have a Back button so I could go back and correct the validation.

I don’t think the browser Back button would work for that, would it?

**Comment by charlieforward9** [comment]
I agree. I just validated some data and had a finger slip once or twice. I expect to add this over the weekend. Updates will be posted in here. @Timothyrichpt

**Comment by charlieforward9** [comment]
### Additional fixes to the validation controls:

- [x] **Classification Toggle**: If the data is good but the class is bad, the data is indicated as 'false' and put into the `invalid` folder. Instead of losing that good data. We could toggle the class and label is at `true`.

- [x] **Reliable Images**: Images do not show up sometimes and throw this error ` Download Image from S3 instead of url only. Thats should improve the reliability. 

- [x] **Fix Previous Image Issues** Take a look at the 'previous image' functionality 

- [x] **Image Count** Indicate how many images are collected and need to be validated.
