### ISSUE TITLE
[Analysis] Upgrades to the PDF for preso

### ISSUE THREAD

**Issue by charlieforward9** [charlieforward9/visualPT#82]
### Discussed in https://github.com/VisualPT/visualPT/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **Timothyrichpt** August  8, 2023</sup>
@charlieforward9 
Can we tidy up the PDF and get it ready for presentation?

[UPGRADES to the PDF   g b_gait_report.docx](https://github.com/VisualPT/visualPT/files/12296837/UPGRADES.to.the.PDF.g.b_gait_report.docx)
</div>

**Comment by charlieforward9** [comment]
@Timothyrichpt I can look into adding [this normative data](https://www.sralab.org/rehabilitation-measures/clinical-test-sensory-interaction-balance#:~:text=NORMATIVE%20DATA,Elderly%20Adults) to the PDF and comparing it to the patient performance, but I would need to collect a 'fall history' entry when the patient is filling out the information that would have a value of (none, few, recurrent). 

What do you think about this?

**Comment by Timothyrichpt** [comment]
Yes, “Fall history“ is an excellent data point to collect as a simple checkbox.


Love Your Life!

Tim


Want to schedule a call with Tim?

Put yourself on Tim's calendar here:

Calendly.com/Grow-With-Tim<https://calendly.com/grow-with-tim>


Tim Richardson, PT

Franchise Regional Consultant

Central Region, USA


FYZICAL LLC

World Headquarters

Bayou Professional Center

1751 Mound Street, <x-apple-data-detectors://2/1> Suite 101<x-apple-data-detectors://2/1>

Sarasota, Florida  34236<x-apple-data-detectors://2/1>


Mobile:  1.941.623.6109<tel:1.941.623.6109>


"Spelled Different Because We Are Different"


FYZICAL is Changing Lives and Changing Healthcare for Millions of Americans by Helping People Live Independently in Their Homes Without Fear of Falling.

On Aug 24, 2023, at 12:56 PM, Charles Richardson ***@***.***> wrote:

﻿

@Timothyrichpt<https://github.com/Timothyrichpt> I can look into adding this normative data<https://www.sralab.org/rehabilitation-measures/clinical-test-sensory-interaction-balance#:~:text=NORMATIVE%20DATA,Elderly%20Adults> to the PDF and comparing it to the patient performance, but I would need to collect a 'fall history' entry when the patient is filling out the information that would have a value of (none, few, recurrent).

What do you think about this?

**Comment by charlieforward9** [comment]
Tracking the fall history enhancement in #88. Which is currently labeled as a feature request and not a core issue. That will be a task for later once the performance is at an acceptable level.

**Comment by charlieforward9** [comment]
For now, I have added the minor changes and **interpretation** section.
